name: imikino-frontend
region: ams
static_sites:
- build_command: npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: Nigorjeanluc/imikino_frontend
  error_document: index.html
  name: imikino-frontend
  routes:
  - path: /
