export const FETCH_CARD_START = 'FETCH_CARD_START';
export const FETCH_CARD_SUCCESS = 'FETCH_CARD_SUCCESS';
export const FETCH_CARD_FAILURE = 'FETCH_CARD_FAILURE';
export const FETCH_CARD_END = 'FETCH_CARD_END';

export const CREATE_CARD_START = 'CREATE_CARD_START';
export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS';
export const CREATE_CARD_FAILURE = 'CREATE_CARD_FAILURE';
export const CREATE_CARD_END = 'CREATE_CARD_END';

export const UPDATE_CARD_START = 'UPDATE_CARD_START';
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS';
export const UPDATE_CARD_FAILURE = 'UPDATE_CARD_FAILURE';
export const UPDATE_CARD_END = 'UPDATE_CARD_END';

export const DELETE_CARD_START = 'DELETE_CARD_START';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILURE = 'DELETE_CARD_FAILURE';
export const DELETE_CARD_END = 'DELETE_CARD_END';