export const FETCH_GOAL_START = 'FETCH_GOAL_START';
export const FETCH_GOAL_SUCCESS = 'FETCH_GOAL_SUCCESS';
export const FETCH_GOAL_FAILURE = 'FETCH_GOAL_FAILURE';
export const FETCH_GOAL_END = 'FETCH_GOAL_END';

export const CREATE_GOAL_START = 'CREATE_GOAL_START';
export const CREATE_GOAL_SUCCESS = 'CREATE_GOAL_SUCCESS';
export const CREATE_GOAL_FAILURE = 'CREATE_GOAL_FAILURE';
export const CREATE_GOAL_END = 'CREATE_GOAL_END';

export const UPDATE_GOAL_START = 'UPDATE_GOAL_START';
export const UPDATE_GOAL_SUCCESS = 'UPDATE_GOAL_SUCCESS';
export const UPDATE_GOAL_FAILURE = 'UPDATE_GOAL_FAILURE';
export const UPDATE_GOAL_END = 'UPDATE_GOAL_END';

export const DELETE_GOAL_START = 'DELETE_GOAL_START';
export const DELETE_GOAL_SUCCESS = 'DELETE_GOAL_SUCCESS';
export const DELETE_GOAL_FAILURE = 'DELETE_GOAL_FAILURE';
export const DELETE_GOAL_END = 'DELETE_GOAL_END';