export const FETCH_GOALS_START = 'FETCH_GOALS_START';
export const FETCH_GOALS_SUCCESS = 'FETCH_GOALS_SUCCESS';
export const FETCH_GOALS_FAILURE = 'FETCH_GOALS_FAILURE';
export const FETCH_GOALS_END = 'FETCH_GOALS_END';
