export const FETCH_LEAGUES_START = 'FETCH_LEAGUES_START';
export const FETCH_LEAGUES_SUCCESS = 'FETCH_LEAGUES_SUCCESS';
export const FETCH_LEAGUES_FAILURE = 'FETCH_LEAGUES_FAILURE';
export const FETCH_LEAGUES_END = 'FETCH_LEAGUES_END';
