export const FETCH_LEAGUE_START = 'FETCH_LEAGUE_START';
export const FETCH_LEAGUE_SUCCESS = 'FETCH_LEAGUE_SUCCESS';
export const FETCH_LEAGUE_FAILURE = 'FETCH_LEAGUE_FAILURE';
export const FETCH_LEAGUE_END = 'FETCH_LEAGUE_END';

export const CREATE_LEAGUE_START = 'CREATE_LEAGUE_START';
export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS';
export const CREATE_LEAGUE_FAILURE = 'CREATE_LEAGUE_FAILURE';
export const CREATE_LEAGUE_END = 'CREATE_LEAGUE_END';

export const UPDATE_LEAGUE_START = 'UPDATE_LEAGUE_START';
export const UPDATE_LEAGUE_SUCCESS = 'UPDATE_LEAGUE_SUCCESS';
export const UPDATE_LEAGUE_FAILURE = 'UPDATE_LEAGUE_FAILURE';
export const UPDATE_LEAGUE_END = 'UPDATE_LEAGUE_END';

export const DELETE_LEAGUE_START = 'DELETE_LEAGUE_START';
export const DELETE_LEAGUE_SUCCESS = 'DELETE_LEAGUE_SUCCESS';
export const DELETE_LEAGUE_FAILURE = 'DELETE_LEAGUE_FAILURE';
export const DELETE_LEAGUE_END = 'DELETE_LEAGUE_END';