export const FETCH_MATCHS_START = 'FETCH_MATCHS_START';
export const FETCH_MATCHS_SUCCESS = 'FETCH_MATCHS_SUCCESS';
export const FETCH_MATCHS_FAILURE = 'FETCH_MATCHS_FAILURE';
export const FETCH_MATCHS_END = 'FETCH_MATCHS_END';
