export const FETCH_MATCH_START = 'FETCH_MATCH_START';
export const FETCH_MATCH_SUCCESS = 'FETCH_MATCH_SUCCESS';
export const FETCH_MATCH_FAILURE = 'FETCH_MATCH_FAILURE';
export const FETCH_MATCH_END = 'FETCH_MATCH_END';

export const CREATE_MATCH_START = 'CREATE_MATCH_START';
export const CREATE_MATCH_SUCCESS = 'CREATE_MATCH_SUCCESS';
export const CREATE_MATCH_FAILURE = 'CREATE_MATCH_FAILURE';
export const CREATE_MATCH_END = 'CREATE_MATCH_END';

export const UPDATE_MATCH_START = 'UPDATE_MATCH_START';
export const UPDATE_MATCH_SUCCESS = 'UPDATE_MATCH_SUCCESS';
export const UPDATE_MATCH_FAILURE = 'UPDATE_MATCH_FAILURE';
export const UPDATE_MATCH_END = 'UPDATE_MATCH_END';

export const DELETE_MATCH_START = 'DELETE_MATCH_START';
export const DELETE_MATCH_SUCCESS = 'DELETE_MATCH_SUCCESS';
export const DELETE_MATCH_FAILURE = 'DELETE_MATCH_FAILURE';
export const DELETE_MATCH_END = 'DELETE_MATCH_END';