export const FETCH_PLAYER_START = 'FETCH_PLAYER_START';
export const FETCH_PLAYER_SUCCESS = 'FETCH_PLAYER_SUCCESS';
export const FETCH_PLAYER_FAILURE = 'FETCH_PLAYER_FAILURE';
export const FETCH_PLAYER_END = 'FETCH_PLAYER_END';

export const CREATE_PLAYER_START = 'CREATE_PLAYER_START';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_FAILURE = 'CREATE_PLAYER_FAILURE';
export const CREATE_PLAYER_END = 'CREATE_PLAYER_END';

export const UPDATE_PLAYER_START = 'UPDATE_PLAYER_START';
export const UPDATE_PLAYER_SUCCESS = 'UPDATE_PLAYER_SUCCESS';
export const UPDATE_PLAYER_FAILURE = 'UPDATE_PLAYER_FAILURE';
export const UPDATE_PLAYER_END = 'UPDATE_PLAYER_END';

export const DELETE_PLAYER_START = 'DELETE_PLAYER_START';
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const DELETE_PLAYER_FAILURE = 'DELETE_PLAYER_FAILURE';
export const DELETE_PLAYER_END = 'DELETE_PLAYER_END';