export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_END = 'FETCH_POSTS_END';

export const FETCH_HEADER_POSTS_START = 'FETCH_HEADER_POSTS_START';
export const FETCH_HEADER_POSTS_SUCCESS = 'FETCH_HEADER_POSTS_SUCCESS';
export const FETCH_HEADER_POSTS_FAILURE = 'FETCH_HEADER_POSTS_FAILURE';
export const FETCH_HEADER_POSTS_END = 'FETCH_HEADER_POSTS_END';

export const FETCH_TRENDING_POSTS_START = 'FETCH_TRENDING_POSTS_START';
export const FETCH_TRENDING_POSTS_SUCCESS = 'FETCH_TRENDING_POSTS_SUCCESS';
export const FETCH_TRENDING_POSTS_FAILURE = 'FETCH_TRENDING_POSTS_FAILURE';
export const FETCH_TRENDING_POSTS_END = 'FETCH_TRENDING_POSTS_END';

export const FETCH_TRANSFER_POSTS_START = 'FETCH_TRANSFER_POSTS_START';
export const FETCH_TRANSFER_POSTS_SUCCESS = 'FETCH_TRANSFER_POSTS_SUCCESS';
export const FETCH_TRANSFER_POSTS_FAILURE = 'FETCH_TRANSFER_POSTS_FAILURE';
export const FETCH_TRANSFER_POSTS_END = 'FETCH_TRANSFER_POSTS_END';

export const FETCH_UNAPPROVED_POSTS_START = 'FETCH_UNAPPROVED_POSTS_START';
export const FETCH_UNAPPROVED_POSTS_SUCCESS = 'FETCH_UNAPPROVED_POSTS_SUCCESS';
export const FETCH_UNAPPROVED_POSTS_FAILURE = 'FETCH_UNAPPROVED_POSTS_FAILURE';
export const FETCH_UNAPPROVED_POSTS_END = 'FETCH_UNAPPROVED_POSTS_END';