export const FETCH_SPORT_START = 'FETCH_SPORT_START';
export const FETCH_SPORT_SUCCESS = 'FETCH_SPORT_SUCCESS';
export const FETCH_SPORT_FAILURE = 'FETCH_SPORT_FAILURE';
export const FETCH_SPORT_END = 'FETCH_SPORT_END';

export const CREATE_SPORT_START = 'CREATE_SPORT_START';
export const CREATE_SPORT_SUCCESS = 'CREATE_SPORT_SUCCESS';
export const CREATE_SPORT_FAILURE = 'CREATE_SPORT_FAILURE';
export const CREATE_SPORT_END = 'CREATE_SPORT_END';

export const UPDATE_SPORT_START = 'UPDATE_SPORT_START';
export const UPDATE_SPORT_SUCCESS = 'UPDATE_SPORT_SUCCESS';
export const UPDATE_SPORT_FAILURE = 'UPDATE_SPORT_FAILURE';
export const UPDATE_SPORT_END = 'UPDATE_SPORT_END';

export const DELETE_SPORT_START = 'DELETE_SPORT_START';
export const DELETE_SPORT_SUCCESS = 'DELETE_SPORT_SUCCESS';
export const DELETE_SPORT_FAILURE = 'DELETE_SPORT_FAILURE';
export const DELETE_SPORT_END = 'DELETE_SPORT_END';