export const FETCH_SPORTS_START = 'FETCH_SPORTS_START';
export const FETCH_SPORTS_SUCCESS = 'FETCH_SPORTS_SUCCESS';
export const FETCH_SPORTS_FAILURE = 'FETCH_SPORTS_FAILURE';
export const FETCH_SPORTS_END = 'FETCH_SPORTS_END';
