export const FETCH_TABLE_START = 'FETCH_TABLE_START';
export const FETCH_TABLE_SUCCESS = 'FETCH_TABLE_SUCCESS';
export const FETCH_TABLE_FAILURE = 'FETCH_TABLE_FAILURE';
export const FETCH_TABLE_END = 'FETCH_TABLE_END';

export const CREATE_TABLE_START = 'CREATE_TABLE_START';
export const CREATE_TABLE_SUCCESS = 'CREATE_TABLE_SUCCESS';
export const CREATE_TABLE_FAILURE = 'CREATE_TABLE_FAILURE';
export const CREATE_TABLE_END = 'CREATE_TABLE_END';

export const UPDATE_TABLE_START = 'UPDATE_TABLE_START';
export const UPDATE_TABLE_SUCCESS = 'UPDATE_TABLE_SUCCESS';
export const UPDATE_TABLE_FAILURE = 'UPDATE_TABLE_FAILURE';
export const UPDATE_TABLE_END = 'UPDATE_TABLE_END';

export const DELETE_TABLE_START = 'DELETE_TABLE_START';
export const DELETE_TABLE_SUCCESS = 'DELETE_TABLE_SUCCESS';
export const DELETE_TABLE_FAILURE = 'DELETE_TABLE_FAILURE';
export const DELETE_TABLE_END = 'DELETE_TABLE_END';
