export const FETCH_TAG_START = 'FETCH_TAG_START';
export const FETCH_TAG_SUCCESS = 'FETCH_TAG_SUCCESS';
export const FETCH_TAG_FAILURE = 'FETCH_TAG_FAILURE';
export const FETCH_TAG_END = 'FETCH_TAG_END';

export const CREATE_TAG_START = 'CREATE_TAG_START';
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
export const CREATE_TAG_FAILURE = 'CREATE_TAG_FAILURE';
export const CREATE_TAG_END = 'CREATE_TAG_END';

export const UPDATE_TAG_START = 'UPDATE_TAG_START';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const UPDATE_TAG_FAILURE = 'UPDATE_TAG_FAILURE';
export const UPDATE_TAG_END = 'UPDATE_TAG_END';

export const DELETE_TAG_START = 'DELETE_TAG_START';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE';
export const DELETE_TAG_END = 'DELETE_TAG_END';