export const FETCH_TOP_SCORER_START = 'FETCH_TOP_SCORER_START';
export const FETCH_TOP_SCORER_SUCCESS = 'FETCH_TOP_SCORER_SUCCESS';
export const FETCH_TOP_SCORER_FAILURE = 'FETCH_TOP_SCORER_FAILURE';
export const FETCH_TOP_SCORER_END = 'FETCH_TOP_SCORER_END';

export const CREATE_TOP_SCORER_START = 'CREATE_TOP_SCORER_START';
export const CREATE_TOP_SCORER_SUCCESS = 'CREATE_TOP_SCORER_SUCCESS';
export const CREATE_TOP_SCORER_FAILURE = 'CREATE_TOP_SCORER_FAILURE';
export const CREATE_TOP_SCORER_END = 'CREATE_TOP_SCORER_END';

export const UPDATE_TOP_SCORER_START = 'UPDATE_TOP_SCORER_START';
export const UPDATE_TOP_SCORER_SUCCESS = 'UPDATE_TOP_SCORER_SUCCESS';
export const UPDATE_TOP_SCORER_FAILURE = 'UPDATE_TOP_SCORER_FAILURE';
export const UPDATE_TOP_SCORER_END = 'UPDATE_TOP_SCORER_END';

export const DELETE_TOP_SCORER_START = 'DELETE_TOP_SCORER_START';
export const DELETE_TOP_SCORER_SUCCESS = 'DELETE_TOP_SCORER_SUCCESS';
export const DELETE_TOP_SCORER_FAILURE = 'DELETE_TOP_SCORER_FAILURE';
export const DELETE_TOP_SCORER_END = 'DELETE_TOP_SCORER_END';
