export const FETCH_TOP_SCORERS_START = 'FETCH_TOP_SCORERS_START';
export const FETCH_TOP_SCORERS_SUCCESS = 'FETCH_TOP_SCORERS_SUCCESS';
export const FETCH_TOP_SCORERS_FAILURE = 'FETCH_TOP_SCORERS_FAILURE';
export const FETCH_TOP_SCORERS_END = 'FETCH_TOP_SCORERS_END';
