export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_END = 'LOGIN_USER_END';

export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const SIGNUP_USER_END = 'SIGNUP_USER_END';

export const LOGOUT_USER_START = 'LOGOUT_START';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_USER_END = 'LOGOUT_END';
