export const FETCH_VIDEO_START = 'FETCH_VIDEO_START';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';
export const FETCH_VIDEO_FAILURE = 'FETCH_VIDEO_FAILURE';
export const FETCH_VIDEO_END = 'FETCH_VIDEO_END';

export const CREATE_VIDEO_START = 'CREATE_VIDEO_START';
export const CREATE_VIDEO_SUCCESS = 'CREATE_VIDEO_SUCCESS';
export const CREATE_VIDEO_FAILURE = 'CREATE_VIDEO_FAILURE';
export const CREATE_VIDEO_END = 'CREATE_VIDEO_END';

export const UPDATE_VIDEO_START = 'UPDATE_VIDEO_START';
export const UPDATE_VIDEO_SUCCESS = 'UPDATE_VIDEO_SUCCESS';
export const UPDATE_VIDEO_FAILURE = 'UPDATE_VIDEO_FAILURE';
export const UPDATE_VIDEO_END = 'UPDATE_VIDEO_END';

export const DELETE_VIDEO_START = 'DELETE_VIDEO_START';
export const DELETE_VIDEO_SUCCESS = 'DELETE_VIDEO_SUCCESS';
export const DELETE_VIDEO_FAILURE = 'DELETE_VIDEO_FAILURE';
export const DELETE_VIDEO_END = 'DELETE_VIDEO_END';
